# Generated by Django 4.1.7 on 2023-03-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0002_alter_maxsulot_tur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korzinka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=30)),
                ('rasm', models.CharField(max_length=200)),
                ('narxi', models.IntegerField()),
                ('son', models.IntegerField()),
                ('tg_id', models.IntegerField()),
                ('ism', models.CharField(max_length=40)),
            ],
        ),
    ]
